apiVersion: v1
kind: ReplicationController   #→ rc descriptor    
metadata:
 name: kubia            #→ Name of the replication controller               
spec:
 replicas: 1                 #→ Desired number of pods       
 selector:                   #→ The pod selector for this rc        
   app: node                        
 template:                   #→ The template for creating a new pod        
   metadata:                         
     labels:                         
       app: node                    
   spec:                             
     containers:                     
     - name: kubia                   
       image: igfdemoel/kubia 
       ports:
        - containerPort: 8080